{% set version = "0.1.0.dev1" %}

package:
  name: chroma-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/chroma-py/chroma-py-{{ version }}.tar.gz
  sha256: 0dc1135332e2ed6e74d7b355c8afa7b85c193a7d5af1cb8b6f79c9e2645912b2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - chroma

about:
  home: https://github.com/jakubsvehla/chroma-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Chroma"

extra:
  recipe-maintainers:
    - ocefpaf
